### ISSUE TITLE
QR code is not always the same size

### ISSUE THREAD

**Issue by SamSamskies** [SamSamskies/PlebPay#1]
Here's an example where it is smaller than the configured size which should be 192px.

<img width="306" alt="Screen Shot 2022-01-14 at 5 12 18 AM" src="https://user-images.githubusercontent.com/3655410/149506488-20fe1125-0df9-430b-b95a-9b404e69b015.png">

Issue is with the `qr-code-styling` library https://github.com/kozakdenys/qr-code-styling/issues/104.

**Comment by SamSamskies** [comment]
Increased the QR code to 200px and the issue is not as bad. Just did that for now as a temp fix.

**Comment by jevidon** [comment]
If it's possible, having the QR full width on mobile and scaled even larger on desktop would be great.
