### ISSUE TITLE
Allow users to pass hex values in URL

### ISSUE THREAD

**Issue by sohomang** [SamSamskies/PlebPay#14]
Customization FTW

By default everything's lime, but switches to the custom color if set

<img width="882" alt="Screen Shot 2022-01-20 at 12 01 08 AM" src="https://user-images.githubusercontent.com/28465517/150232217-64a45081-fd30-4a67-a867-3a03c7f02fae.png">

**Comment by SamSamskies** [comment]
Can you update the create paywall form designs to add additional optional fields for custom color and preview image?

**Comment by sohomang** [comment]
Added color picker! The square paint bucket button is a simple [HTML5 color picker](https://www.w3schools.com/colors/colors_picker.asp). Hex value should be pre-filled with the default color. When changing the default color, UI elements ("Create Paywall", color picker) should change colors as well, right away. #15 will be useful there

- Mobile: https://www.figma.com/file/ZSdrYE1jzSYN6c4y2R7vIF/Paywall?node-id=212%3A380
- Desktop: https://www.figma.com/file/ZSdrYE1jzSYN6c4y2R7vIF/Paywall?node-id=210%3A1179

**Comment by SamSamskies** [comment]
NACK on the color picker. Gonna try and keep the app simple. I'll add ability to set button colors with query params.

**Comment by SamSamskies** [comment]
User's can now set a brand color with query params. Some examples.

https://plebpay.com/ccc2c527-8c1c-4b74-9419-f040f3b61fa8?brandColor=bitcoin
https://plebpay.com/2f077162-47ac-4d1c-96ee-7ed2491b76f5?brandColor=865efc
https://plebpay.com/21cbff55-2407-4394-a727-c8ed67dd5ab8?brandColor=deepskyblue
