### ISSUE TITLE
Switch button text color based on background color

### ISSUE THREAD

**Issue by sohomang** [SamSamskies/PlebPay#15]
Related to #14. That's for the "Enter for $1.00" button. Increases readability.

Here's a cool code snippet that does just that: https://stackoverflow.com/questions/11867545/change-text-color-based-on-brightness-of-the-covered-background-area

<img width="316" alt="Screen Shot 2022-01-20 at 12 01 59 AM" src="https://user-images.githubusercontent.com/28465517/150232289-c3803d7b-a974-4e05-973b-d8c4189d7cf7.png">

**Comment by SamSamskies** [comment]
done
