### ISSUE TITLE
Style for splash & settings pages

### ISSUE THREAD

**Issue by sohomang** [SamSamskies/PlebPay#17]
Made it juicy

- Mobile: https://www.figma.com/file/ZSdrYE1jzSYN6c4y2R7vIF/Paywall?node-id=212%3A341
- Desktop: https://www.figma.com/file/ZSdrYE1jzSYN6c4y2R7vIF/Paywall?node-id=210%3A173

**Comment by SamSamskies** [comment]
![juicy](https://user-images.githubusercontent.com/3655410/150269652-1fb7112a-c12b-47bb-849d-06146ff86357.gif)

**Comment by sohomang** [comment]
Updated settings copy

<img width="514" alt="Screen Shot 2022-01-20 at 10 55 50 AM" src="https://user-images.githubusercontent.com/28465517/150315834-30231f34-2b91-4c05-bb88-e377e5adf2fc.png">
