### ISSUE TITLE
Allow users to set a background image

### ISSUE THREAD

**Issue by sohomang** [SamSamskies/PlebPay#18]
No BD so no manual image upload, but users can drop an URL if they have one. This is the only optional field. Contrary to the color picker, there is no preview at the Settings step

- Mobile: https://www.figma.com/file/ZSdrYE1jzSYN6c4y2R7vIF/Paywall?node-id=212%3A380
- Desktop: https://www.figma.com/file/ZSdrYE1jzSYN6c4y2R7vIF/Paywall?node-id=210%3A1179

**Comment by SamSamskies** [comment]
Axing this. Wanna try and keep the app simple. We can reopen in the future if there's a demand for it.
