### ISSUE TITLE
Use Montserrat for textfields and buttons

### ISSUE THREAD

**Issue by sohomang** [SamSamskies/PlebPay#20]
If my designer eyes don't lie, this looks like Arial

<img width="452" alt="Screen Shot 2022-01-21 at 12 00 24 PM" src="https://user-images.githubusercontent.com/28465517/150518692-00092033-3d08-4ef5-94cf-36dce43799da.png">
<img width="270" alt="Screen Shot 2022-01-21 at 12 00 44 PM" src="https://user-images.githubusercontent.com/28465517/150518696-29506d8b-8768-4ed9-b0a2-1cc38623ab9e.png">
<img width="452" alt="Screen Shot 2022-01-21 at 12 00 24 PM" src="https://user-images.githubusercontent.com/28465517/150518727-099d2ba5-9f31-4df7-bcc7-fc125d863c1c.png">

(jk i just did `right click > inspect`)

**Comment by SamSamskies** [comment]
fixed
