### ISSUE TITLE
Bump paragraph line height for readability

### ISSUE THREAD

**Issue by sohomang** [SamSamskies/PlebPay#21]
Body paragraphs of size 16px like these should use a line height of 25px for better readability

<img width="934" alt="Screen Shot 2022-01-21 at 12 07 36 PM" src="https://user-images.githubusercontent.com/28465517/150518889-d8de0f82-1806-4863-bcd8-3dac7ef9e792.png">

<img width="628" alt="Screen Shot 2022-01-21 at 12 07 43 PM" src="https://user-images.githubusercontent.com/28465517/150519005-fd035451-05e2-4f1e-bb1a-f1e7763ea908.png">

**Comment by SamSamskies** [comment]
fixed
