### ISSUE TITLE
Error state for users who can't receive funds

### ISSUE THREAD

**Issue by sohomang** [SamSamskies/PlebPay#22]
After the username step, can we check if the user has `canReceive` and throw an error state when they can't? Users who can't receive are currently forwarded to the settings page but even after filling the info it freezes when they hit "Create Paywall"

<img width="541" alt="Screen Shot 2022-01-21 at 12 28 03 PM" src="https://user-images.githubusercontent.com/28465517/150519503-f1604476-fa07-42b5-a187-99a8c72416d8.png">

**Comment by sohomang** [comment]
We can use the same layout as the 404 page, with different copy. Something like: 
> Doh! This Strike user can't receive money yet.

**Comment by SamSamskies** [comment]
Sir, there's already an issue for that https://github.com/SamSamskies/PlebPay/issues/6
