### ISSUE TITLE
QR code doesn't work with Breez and Phoenix wallet

### ISSUE THREAD

**Issue by gregorsbueezer** [SamSamskies/PlebPay#24]
I can't scan the QR code with my Breez or Phoenix wallet. Copy paste works but scanning would be more convenient.

**Comment by SamSamskies** [comment]
hmmmm it works fine for me with Breez. I don't have Phoenix wallet to test. Can you post a screenshot of a specific QR that you are having problems with? Could be a problem with the specific QR code that was generated.

**Comment by gregorsbueezer** [comment]
My friend couldn't scan it aswell (Breez).
![grafik](https://user-images.githubusercontent.com/86912958/150643565-465c1eea-316e-4186-915d-b8bc16e50526.png)

**Comment by SamSamskies** [comment]
This QR code works fine for me with Breez, so not sure what I can do.

**Comment by SamSamskies** [comment]
Looks like it's Android phone scanners that have problems with these QR codes https://github.com/kozakdenys/qr-code-styling/issues/105. That would explain why I couldn't reproduce the error. I'll probably swap out this library with another library.

**Comment by SamSamskies** [comment]
Probably gonna swap out `qr-code-styling` with `qrcode.react`.
