### ISSUE TITLE
"Amount" unit display

### ISSUE THREAD

**Issue by szollo** [SamSamskies/PlebPay#3]
Might be worth specifying "Amount" in the unit used (in this case USD).

**Comment by SamSamskies** [comment]
I was planning on doing that, but then I didn't cause I thought it might be confusing for the users that have USDT as their active currency. Cause then on the paywall screen if I show `Enter for $USDT 0.01` people might think they actually have to pay using USDT, but you can't actually do that unless you're another Strike user with USDT as their active currency. I was hoping leaving it blank would imply the amount of "units" of whatever your active currency is in Strike. Not sure the best way to convey that to the user.

**Comment by SamSamskies** [comment]
I guess we'll eventually have to deal with a bunch of different currencies though. I'll go ahead and display the actual currency and hopefully people will figure it out. Now I understand why Twitter displays an estimate of the number of sats on the tip button.

**Comment by SamSamskies** [comment]
deployed 🚀
