### ISSUE TITLE
Improved Error Message When User Is Private

### ISSUE THREAD

**Issue by JimmyMow** [SamSamskies/PlebPay#40]
Currently, if a user enters a username that is set to `private`, PlebPay displays an error message that this user does not exist.

This is slightly misleading as they do exist, they just need to ensure their profile is `public` so they can receive Tips.

**Comment by SamSamskies** [comment]
Do you have an example username? Error message should say `Doh! <PRIVATE_USERNAME> currently can't create paywalls. Strike accounts must be public in order to create paywalls.`.

**Comment by SamSamskies** [comment]
Like this https://www.plebpay.com/create/asdfasdf

![Screen Shot 2022-02-01 at 9 14 45 AM](https://user-images.githubusercontent.com/3655410/151995575-a906740e-b407-475c-8b6c-87d73c148eb4.png)

**Comment by SamSamskies** [comment]
User does not exist message should only be displayed when backend responds with 404 like this https://www.plebpay.com/create/asdfasdfasdfasdf

![Screen Shot 2022-02-01 at 9 16 13 AM](https://user-images.githubusercontent.com/3655410/151995814-e53208a7-e131-457e-ba5a-28fc8b3c66ae.png)
