### ISSUE TITLE
Add link to download Strike at paywall page

### ISSUE THREAD

**Issue by sohomang** [SamSamskies/PlebPay#8]
We should advertise our wallet in case users don't have one. We can do that through a bottom-screen instruction line:
- Mobile: https://www.figma.com/file/ZSdrYE1jzSYN6c4y2R7vIF/Paywall?node-id=2%3A15
- Desktop: https://www.figma.com/file/ZSdrYE1jzSYN6c4y2R7vIF/Paywall?node-id=2%3A1051

**Comment by SamSamskies** [comment]
I think the CTA should be to download Strike. Unless we have a link that lists Strike along with a list of other ⚡️ wallets.

**Comment by sohomang** [comment]
Yup after our discussion I updated the copy to be Strike-specific. Just forgot to update the Desktop designs and the screenshot above (deleted)

> New to Bitcoin? **Click here** to download Strike and get started.
