### ISSUE TITLE
Add terms and privacy notice to the settings page

### ISSUE THREAD

**Issue by sohomang** [SamSamskies/PlebPay#9]
Links to be defined, not sure if it should point to the API terms or the consumer terms

- Mobile: https://www.figma.com/file/ZSdrYE1jzSYN6c4y2R7vIF/Paywall?node-id=212%3A380
- Desktop: https://www.figma.com/file/ZSdrYE1jzSYN6c4y2R7vIF/Paywall?node-id=210%3A1179

**Comment by SamSamskies** [comment]
Why do we need a link for the API terms? It seems those terms are meant for the devs themselves and no the users of apps that the devs make.

**Comment by sohomang** [comment]
After confirmation by legal, we should point to our consumer Terms and PN. Updated the copy accordingly
